### PR TITLE
To-Do list implementation

### PR DESCRIPTION
**Pull request by Pali-Pali**
Hi There! This is my first pull request.
You will find 3 files in here: HTML, CSS, JavaScript. 

The project is a "To-Do-List" application.
Functions include:  Add, Delete and Mark Task As Complete.

Your reviews are highly appreciated.
Thank you in advance.

-Palesa

### CODE REVIEW

**Review by RolivhuwaMuzila — CHANGES_REQUESTED** [review]
Hi Palesa,

Great job on your first pull request! It's awesome to see your "To-Do-List" application in action. I noticed the functionality to Add, Delete, and Mark Tasks as Complete is working well.

However, based on the requirements for the project, we need to ensure that the setup includes Node.js and a simple server, along with the JavaScript functionality. It would be great if you could confirm that the Node.js setup is in place, and if the simple server is functioning as expected.

Once that's added, we can proceed with further reviews and improvements. Keep up the good work!

Looking forward to seeing the next iteration.

Thank you!

-Rolivhuwa

**Review by Xolanisyav04 — APPROVED** [review]
Well done Palesa you have done a great job!

**Comment by Pali-Pali** [comment]
Thank you Xolani

**Review by RolivhuwaMuzila — COMMENTED** [review]
Hi Palesa,

Thank you for making the changes I requested! I’ve tested the updates, and the Node.js setup and server functionality are now working as expected. Great job on addressing the feedback so quickly.

Everything looks good from my side. Let's go ahead with the next steps.

Keep up the excellent work!

Best,
Rolivhuwa

**Review by RolivhuwaMuzila — APPROVED** [review]

**Review by atlehang66 — APPROVED** [review]
HI @Pali-Pali , I am exited to approve your project. all project requirements have been met. congratulations on this achievements.

**Review by asandan8106 — APPROVED** [review]
nice work Pali. you can now merge and deploy , Good luck!!

**Pull request merged**
